# Generated by Django 3.2.8 on 2021-10-24 03:42

from django.conf import settings
from django.db import migrations


def update_site_info(apps, schema_editor):
    Site = apps.get_model("sites", "Site")
    default_site = Site.objects.first()
    default_site.domain = "church-ims.herokuapp.com"
    default_site.name = settings.SITE_NAME
    default_site.save()


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.RunPython(update_site_info),
    ]
