# Generated by Django 3.2.8 on 2021-10-24 03:42

from django.conf import settings
from django.db import migrations


def update_site_info(apps, schema_editor):
    Site = apps.get_model("sites", "Site")
    site_data = {
        "id": settings.SITE_ID,
        "domain": "church-ims.herokuapp.com",
        "name": settings.SITE_NAME,
    }

    default_site = Site.objects.first()
    if default_site is not None:
        default_site.update(**site_data)
    else:
        Site.objects.create(**site_data)

    assert Site.objects.first().name == site_data["name"]


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.RunPython(update_site_info),
    ]
