# Generated by Django 3.2.5 on 2021-07-03 17:56

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                help_text="Enter a valid phone number that starts with a country code.",
                max_length=50,
                region=None,
            ),
        ),
    ]
