# Generated by Django 3.2.4 on 2021-06-27 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("children", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="dob",
            field=models.DateField(
                help_text="The format should be DD/MM/YYYY",
                verbose_name="date of birth",
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="slug",
            field=models.SlugField(
                error_messages={"unique": "A child with that username already exists."},
                help_text="Enter a unique username for your child. Don't use full-stops/periods",
                unique=True,
                verbose_name="username",
            ),
        ),
        migrations.AlterField(
            model_name="parentchildrelationship",
            name="relationship_type",
            field=models.ForeignKey(
                help_text="How are you related to the child?",
                on_delete=django.db.models.deletion.PROTECT,
                to="children.relationshiptype",
            ),
        ),
    ]
