# Generated by Django 3.2.4 on 2021-06-24 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='familyrelationship_creators', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Enter a URL-friendly name', unique=True, verbose_name='username')),
                ('full_name', models.CharField(max_length=300)),
                ('dob', models.DateField(verbose_name='date of birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('C', 'Custom'), ('P', 'Prefer not to say')], max_length=2)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_creators', to=settings.AUTH_USER_MODEL)),
                ('family_members', models.ManyToManyField(related_name='_people_person_family_members_+', through='people.FamilyRelationship', to='people.Person')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_editors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'people',
                'ordering': ['slug'],
            },
        ),
        migrations.AddField(
            model_name='familyrelationship',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='people.person'),
        ),
        migrations.AddField(
            model_name='familyrelationship',
            name='relationship_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.relationshiptype'),
        ),
        migrations.AddField(
            model_name='familyrelationship',
            name='relative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reverse_relationships', to='people.person'),
        ),
        migrations.AddField(
            model_name='familyrelationship',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='familyrelationship_editors', to=settings.AUTH_USER_MODEL),
        ),
    ]
