# Generated by Django 3.2.5 on 2021-07-01 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationship_creators', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'family_relationship',
            },
        ),
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'relationship_type',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('username', models.SlugField(default=uuid.uuid4, error_messages={'unique': 'A user with that username already exists.'}, help_text="Enter a unique username. Don't use full-stops/periods", unique=True)),
                ('full_name', models.CharField(max_length=300, null=True)),
                ('dob', models.DateField(null=True, verbose_name='date of birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('C', 'Custom'), ('P', 'Prefer not to say')], max_length=2, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_creators', to=settings.AUTH_USER_MODEL)),
                ('family_members', models.ManyToManyField(related_name='_people_person_family_members_+', through='people.FamilyRelationship', to='people.Person')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_editors', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'people',
                'ordering': ['username'],
            },
        ),
        migrations.AddField(
            model_name='familyrelationship',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person'),
        ),
        migrations.AddField(
            model_name='familyrelationship',
            name='relationship_type',
            field=models.ForeignKey(help_text='How are you related to the person?', on_delete=django.db.models.deletion.PROTECT, to='people.relationshiptype'),
        ),
        migrations.AddField(
            model_name='familyrelationship',
            name='relative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatives', to='people.person'),
        ),
        migrations.AddField(
            model_name='familyrelationship',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationship_editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='familyrelationship',
            constraint=models.UniqueConstraint(fields=('person', 'relative'), name='people_familyrelationship_unique_relationships'),
        ),
        migrations.AddConstraint(
            model_name='familyrelationship',
            constraint=models.CheckConstraint(check=models.Q(('person', django.db.models.expressions.F('relative')), _negated=True), name='people_familyrelationship_prevent_self_relationship'),
        ),
    ]
