# Generated by Django 3.2.4 on 2021-06-23 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['username'], 'verbose_name_plural': 'people'},
        ),
    ]
