# Generated by Django 3.2.7 on 2021-10-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0002_interpersonalrelationship"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="interpersonalrelationship",
            constraint=models.UniqueConstraint(
                fields=("person", "relative"),
                name="people_unique_interpersonalrelationship",
            ),
        ),
    ]
