# Generated by Django 3.2.5 on 2021-07-10 17:34

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0002_auto_20210703_2043"),
    ]

    operations = [
        migrations.AddField(
            model_name="familyrelationship",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="familyrelationship",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="familyrelationship",
            name="relationship_type",
            field=models.ForeignKey(
                help_text="How is the person related to you?",
                on_delete=django.db.models.deletion.PROTECT,
                to="people.relationshiptype",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="dob",
            field=models.DateField(
                help_text="Please use the following format: <em>DD/MM/YYYY.</em>",
                null=True,
                validators=[core.validators.validate_date_of_birth],
                verbose_name="date of birth",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="full_name",
            field=models.CharField(
                max_length=300,
                null=True,
                validators=[core.validators.validate_full_name],
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="username",
            field=models.SlugField(
                default=uuid.uuid4,
                error_messages={"unique": "A user with that username already exists."},
                help_text="Enter a human-readable unique username without any full-stops",
                unique=True,
            ),
        ),
    ]
