# Generated by Django 3.2.7 on 2021-10-20 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("people", "0006_alter_person_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="user_account",
            field=models.OneToOneField(
                help_text="This person's user account.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
