# Generated by Django 3.2.4 on 2021-06-26 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildTemperature',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temp', models.DecimalField(decimal_places=2, help_text="A person's body temperature in degrees celsius", max_digits=4, verbose_name='temperature record')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='children.child')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childtemperature_creators', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childtemperature_editors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ChildrenTemperature',
            },
        ),
    ]
