# Generated by Django 3.2.5 on 2021-07-02 17:59

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BodyTemperature",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "temp",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="A person's body temperature in degrees celsius",
                        max_digits=4,
                        verbose_name="temperature record",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="temperature_creators",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="people.person"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "body temperature",
                "db_table": "body_temperature",
            },
        ),
    ]
