# Generated by Django 3.2.7 on 2021-10-10 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import records.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemperatureRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "body_temperature",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The person's body temperature in degrees celsius.",
                        max_digits=4,
                        validators=[records.validators.validate_human_body_temperature],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The user who created this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="people.person"
                    ),
                ),
            ],
            options={
                "db_table": "records_temperature",
                "ordering": ["person__username", "created_at"],
            },
        ),
    ]
