# Generated by Django 3.2.5 on 2021-07-14 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="bodytemperature",
            table="records_body_temperature",
        ),
    ]
